- name: deleting old directory
  ansible.builtin.file:
   path: "{{ app_location }}"
   state: absent 



- name: creating a new directory 
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory

- name: unarchive a zip file 
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip
    dest: /app
    remote_src: yes